metadata:
  name: cancer-dataset-jovyan
spec:
  origin_url: git://github.com/Dakshata47/STT_a9.git#refs/heads/main
  desired_state: online
  source: git://github.com/Dakshata47/STT_a9.git#refs/heads/main
  conda: ''
  functions:
  - url: data_prep.py
    name: data-prep
    kind: job
    image: mlrun/mlrun
  - url: trainer.py
    name: trainer
    kind: job
    image: mlrun/mlrun
    handler: train
  - url: serving.py
    name: serving
    kind: serving
    image: mlrun/mlrun
kind: project
